---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hp.
--- DateTime: 2024/6/23 12:02
---

--- 判断库存是否充足 --- redis Id 的 key
--- 优惠券Id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

--- 库存Id
local stockKey = 'seckill:stock:' .. voucherId
--- 订单Id
local orderKey = 'seckill:order:' .. voucherId
--- 判断库存是否大于0
local stock = tonumber(redis.call('get', stockKey))
if (stock and stock <= 0) then
    return 1
end
--- 判断用户 是否下单
if(redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
--- 进行扣库存 incrby
redis.call('incrby',stockKey, -1)
--- 下单 （保存用户)
redis.call('sadd',orderKey,userId)

--- 发送到消息队列里
redis.call('xadd','stream.orders','*','userId',userId, 'voucherId',voucherId, 'id', orderId)
return 0
