---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hp.
--- DateTime: 2024/6/23 12:02
---

--- 判断库存是否充足 --- redis Id 的 key
--- 优惠券Id
local Id = ARGV[1]
local userId = ARGV[2]

--- 库存Id
local stockId = 'seckill:stock:' .. Id
--- 订单Id
local orderId = 'seckill:order:' .. Id
--- 判断库存是否大于0
local stock = tonumber(redis.call('get', stockId))
if (stock and stock <= 0) then
    return 1
end
--- 判断用户 是否下单
if(redis.call('sismember', orderId, userId) == 1) then
    return 2
end
--- 进行扣库存 incrby
redis.call('incrby',stockId, -1)
--- 下单 （保存用户)
redis.call('sadd',orderId,userId)
return 0
